/*
 * This source file was generated by the Gradle 'init' task
 */
package sarahmath;

import java.util.HashMap;
import java.util.Map;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        Map<String, Integer> lessonHash = new HashMap<>();
        System.out.println(new App().getGreeting());

        GetLesson gl = new GetLesson();
        lessonHash = gl.getLesson();  // make a hash

        ProblemGenerator pg = new ProblemGenerator();
        System.out.println("lessonHash[random]: " + lessonHash.get("random").intValue());
        System.out.println("lessonHash[function]: " + lessonHash.get("function").intValue());
        System.out.println("lessonHash[problems]: " + lessonHash.get("problems").intValue());

        if (lessonHash.get("function").intValue() == 0) {
          pg.setlessonFunction(BasicMath.ADD);
        } else if (lessonHash.get("function").intValue() == 1) {
          pg.setlessonFunction(BasicMath.SUB);
        } else if (lessonHash.get("function").intValue() == 2) {
          pg.setlessonFunction(BasicMath.MUL);
        } else if (lessonHash.get("function").intValue() == 3) {
          pg.setlessonFunction(BasicMath.DIV);
        }
        if (lessonHash.get("random").intValue() == 1) {
          pg.setrandomProblem(true);
        } 

        pg.setnumProblems(lessonHash.get("problems").intValue());

        try {
          pg.problemSet();
        } catch (Exception ex) {            
          System.out.println("Exception - " + ex.getMessage());
        }        
    }
   
}
